-- Gen.lua
-- @Author : Dencer (tdaddon@163.com)
-- @Link   : https://dengsir.github.io
-- @Date   : 9/23/2020, 1:27:46 PM
--
---@type ns
local ns = select(2, ...)

local LE_ITEM_CLASS_ARMOR = 4
local LE_ITEM_CLASS_WEAPON = 2

local INFO = {
    -- Dust
    ['i:10940'] = { -- Strange Dust
        minLevel = 0,
        maxLevel = 20,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 5,
                maxItemLevel = 15,
                matRate = 0.800,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.200,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 16,
                maxItemLevel = 20,
                matRate = 0.750,
                minAmount = 2,
                maxAmount = 3,
                amountOfMats = 1.850,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 21,
                maxItemLevel = 25,
                matRate = 0.750,
                minAmount = 4,
                maxAmount = 6,
                amountOfMats = 3.750,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 5,
                maxItemLevel = 15,
                matRate = 0.200,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 0.300,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 16,
                maxItemLevel = 20,
                matRate = 0.200,
                minAmount = 2,
                maxAmount = 3,
                amountOfMats = 0.500,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 21,
                maxItemLevel = 25,
                matRate = 0.150,
                minAmount = 4,
                maxAmount = 6,
                amountOfMats = 0.750,
            },
        },
    },
    ['i:11083'] = { -- Soul Dust
        minLevel = 21,
        maxLevel = 30,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 26,
                maxItemLevel = 30,
                matRate = 0.750,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.100,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 31,
                maxItemLevel = 35,
                matRate = 0.750,
                minAmount = 2,
                maxAmount = 5,
                amountOfMats = 2.550,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 26,
                maxItemLevel = 30,
                matRate = 0.200,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 0.300,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 31,
                maxItemLevel = 35,
                matRate = 0.200,
                minAmount = 2,
                maxAmount = 5,
                amountOfMats = 0.700,
            },
        },
    },
    ['i:11137'] = { -- Vision Dust
        minLevel = 31,
        maxLevel = 40,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 36,
                maxItemLevel = 40,
                matRate = 0.750,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.100,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 41,
                maxItemLevel = 45,
                matRate = 0.750,
                minAmount = 2,
                maxAmount = 5,
                amountOfMats = 2.550,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 36,
                maxItemLevel = 40,
                matRate = 0.200,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 0.300,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 41,
                maxItemLevel = 45,
                matRate = 0.200,
                minAmount = 2,
                maxAmount = 5,
                amountOfMats = 0.700,
            },
        },
    },
    ['i:11176'] = { -- Dream Dust
        minLevel = 41,
        maxLevel = 50,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 46,
                maxItemLevel = 50,
                matRate = 0.750,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.100,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 51,
                maxItemLevel = 55,
                matRate = 0.750,
                minAmount = 2,
                maxAmount = 5,
                amountOfMats = 2.550,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 46,
                maxItemLevel = 50,
                matRate = 0.200,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 0.300,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 51,
                maxItemLevel = 55,
                matRate = 0.200,
                minAmount = 2,
                maxAmount = 5,
                amountOfMats = 0.700,
            },
        },
    },
    ['i:16204'] = { -- Illusion Dust
        minLevel = 51,
        maxLevel = 60,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 56,
                maxItemLevel = 60,
                matRate = 0.750,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.100,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 61,
                maxItemLevel = 65,
                matRate = 0.750,
                minAmount = 2,
                maxAmount = 5,
                amountOfMats = 2.550,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 56,
                maxItemLevel = 60,
                matRate = 0.200,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 0.300,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 61,
                maxItemLevel = 65,
                matRate = 0.200,
                minAmount = 2,
                maxAmount = 5,
                amountOfMats = 0.700,
            },
        },
    },

    -- Essences
    ['i:10938'] = { -- Lesser Magic Essence
        minLevel = 0,
        maxLevel = 10,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 5,
                maxItemLevel = 15,
                matRate = 0.200,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 0.300,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 5,
                maxItemLevel = 15,
                matRate = 0.800,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.200,
            },
        },
    },
    ['i:10939'] = { -- Greater Magic Essence
        minLevel = 11,
        maxLevel = 15,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 16,
                maxItemLevel = 20,
                matRate = 0.200,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 0.300,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 16,
                maxItemLevel = 20,
                matRate = 0.750,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.100,
            },
        },
    },
    ['i:10998'] = { -- Lesser Astral Essence
        minLevel = 16,
        maxLevel = 20,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 21,
                maxItemLevel = 25,
                matRate = 0.150,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 0.200,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 21,
                maxItemLevel = 25,
                matRate = 0.750,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.100,
            },
        },
    },
    ['i:11082'] = { -- Greater Astral Essence
        minLevel = 21,
        maxLevel = 25,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 26,
                maxItemLevel = 30,
                matRate = 0.200,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 0.300,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 26,
                maxItemLevel = 30,
                matRate = 0.750,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.100,
            },
        },
    },
    ['i:11134'] = { -- Lesser Mystic Essence
        minLevel = 26,
        maxLevel = 30,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 31,
                maxItemLevel = 35,
                matRate = 0.200,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 0.300,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 31,
                maxItemLevel = 35,
                matRate = 0.750,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.100,
            },
        },
    },
    ['i:11135'] = { -- Greater Mystic Essence
        minLevel = 31,
        maxLevel = 35,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 36,
                maxItemLevel = 40,
                matRate = 0.200,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 0.300,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 36,
                maxItemLevel = 40,
                matRate = 0.750,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.100,
            },
        },
    },
    ['i:11174'] = { -- Lesser Nether Essence
        minLevel = 36,
        maxLevel = 40,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 41,
                maxItemLevel = 45,
                matRate = 0.200,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 0.300,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 41,
                maxItemLevel = 45,
                matRate = 0.750,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.100,
            },
        },
    },
    ['i:11175'] = { -- Greater Nether Essence
        minLevel = 41,
        maxLevel = 45,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 46,
                maxItemLevel = 50,
                matRate = 0.250,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 0.300,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 46,
                maxItemLevel = 50,
                matRate = 0.750,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.100,
            },
        },
    },
    ['i:16202'] = { -- Lesser Eternal Essence
        minLevel = 46,
        maxLevel = 50,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 51,
                maxItemLevel = 55,
                matRate = 0.200,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 0.300,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 51,
                maxItemLevel = 55,
                matRate = 0.750,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.100,
            },
        },
    },
    ['i:16203'] = { -- Greater Eternal Essence
        minLevel = 51,
        maxLevel = 60,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 56,
                maxItemLevel = 60,
                matRate = 0.200,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 0.300,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 61,
                maxItemLevel = 65,
                matRate = 0.200,
                minAmount = 2,
                maxAmount = 3,
                amountOfMats = 0.500,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 56,
                maxItemLevel = 60,
                matRate = 0.750,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.100,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 61,
                maxItemLevel = 65,
                matRate = 0.750,
                minAmount = 2,
                maxAmount = 3,
                amountOfMats = 1.850,
            },
        },
    },

    -- Shards
    ['i:10978'] = { -- Small Glimmering Shard
        minLevel = 0,
        maxLevel = 20,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 16,
                maxItemLevel = 20,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.050,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 21,
                maxItemLevel = 25,
                matRate = 0.100,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.100,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 3,
                minItemLevel = 5,
                maxItemLevel = 25,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 1.000,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 16,
                maxItemLevel = 20,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.050,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 21,
                maxItemLevel = 25,
                matRate = 0.100,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.100,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 3,
                minItemLevel = 5,
                maxItemLevel = 25,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 1.000,
            },
        },
    },
    ['i:11084'] = { -- Large Glimmering Shard
        minLevel = 21,
        maxLevel = 25,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 26,
                maxItemLevel = 30,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.050,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 3,
                minItemLevel = 26,
                maxItemLevel = 30,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 1.000,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 26,
                maxItemLevel = 30,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.050,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 3,
                minItemLevel = 26,
                maxItemLevel = 30,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 1.000,
            },
        },
    },
    ['i:11138'] = { -- Small Glowing Shard
        minLevel = 26,
        maxLevel = 30,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 31,
                maxItemLevel = 35,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.050,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 3,
                minItemLevel = 31,
                maxItemLevel = 35,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 1.000,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 31,
                maxItemLevel = 35,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.050,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 3,
                minItemLevel = 31,
                maxItemLevel = 35,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 1.000,
            },
        },
    },
    ['i:11139'] = { -- Large Glowing Shard
        minLevel = 31,
        maxLevel = 35,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 36,
                maxItemLevel = 40,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.050,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 3,
                minItemLevel = 36,
                maxItemLevel = 40,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 1.000,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 36,
                maxItemLevel = 40,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.050,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 3,
                minItemLevel = 36,
                maxItemLevel = 40,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 1.000,
            },
        },
    },
    ['i:11177'] = { -- Small Radiant Shard
        minLevel = 36,
        maxLevel = 40,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 41,
                maxItemLevel = 45,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.050,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 3,
                minItemLevel = 41,
                maxItemLevel = 45,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 1.000,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 4,
                minItemLevel = 40,
                maxItemLevel = 45,
                matRate = 1.000,
                minAmount = 2,
                maxAmount = 4,
                amountOfMats = 3.000,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 41,
                maxItemLevel = 45,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.050,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 3,
                minItemLevel = 41,
                maxItemLevel = 45,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 1.000,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 4,
                minItemLevel = 40,
                maxItemLevel = 45,
                matRate = 1.000,
                minAmount = 2,
                maxAmount = 4,
                amountOfMats = 3.000,
            },
        },
    },
    ['i:11178'] = { -- Large Radiant Shard
        minLevel = 41,
        maxLevel = 45,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 46,
                maxItemLevel = 50,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.050,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 3,
                minItemLevel = 46,
                maxItemLevel = 50,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 1.000,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 4,
                minItemLevel = 46,
                maxItemLevel = 50,
                matRate = 1.000,
                minAmount = 2,
                maxAmount = 4,
                amountOfMats = 3.000,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 46,
                maxItemLevel = 50,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.050,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 3,
                minItemLevel = 46,
                maxItemLevel = 50,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 1.000,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 4,
                minItemLevel = 46,
                maxItemLevel = 50,
                matRate = 1.000,
                minAmount = 2,
                maxAmount = 4,
                amountOfMats = 3.000,
            },
        },
    },
    ['i:14343'] = { -- Small Brilliant Shard
        minLevel = 46,
        maxLevel = 50,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 51,
                maxItemLevel = 55,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.030,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 3,
                minItemLevel = 51,
                maxItemLevel = 55,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 1.000,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 4,
                minItemLevel = 51,
                maxItemLevel = 55,
                matRate = 1.000,
                minAmount = 2,
                maxAmount = 4,
                amountOfMats = 3.000,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 51,
                maxItemLevel = 55,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.030,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 3,
                minItemLevel = 51,
                maxItemLevel = 55,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 1.000,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 4,
                minItemLevel = 51,
                maxItemLevel = 55,
                matRate = 1.000,
                minAmount = 2,
                maxAmount = 4,
                amountOfMats = 3.000,
            },
        },
    },
    ['i:14344'] = { -- Large Brilliant Shard
        minLevel = 51,
        maxLevel = 60,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 2,
                minItemLevel = 56,
                maxItemLevel = 65,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.050,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 3,
                minItemLevel = 56,
                maxItemLevel = 65,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.995,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 2,
                minItemLevel = 56,
                maxItemLevel = 65,
                matRate = 0.050,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.050,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 3,
                minItemLevel = 56,
                maxItemLevel = 65,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.995,
            },
        },
    },

    -- Crystals
    ['i:20725'] = { -- Nexus Crystal
        minLevel = 51,
        maxLevel = 60,
        sourceInfo = {
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 3,
                minItemLevel = 56,
                maxItemLevel = 65,
                matRate = 0.005,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.005,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 4,
                minItemLevel = 56,
                maxItemLevel = 60,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 1.000,
            },
            {
                classId = LE_ITEM_CLASS_ARMOR,
                quality = 4,
                minItemLevel = 61,
                maxItemLevel = 95,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.666,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 3,
                minItemLevel = 56,
                maxItemLevel = 65,
                matRate = 0.005,
                minAmount = 1,
                maxAmount = 1,
                amountOfMats = 0.005,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 4,
                minItemLevel = 56,
                maxItemLevel = 60,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.000,
            },
            {
                classId = LE_ITEM_CLASS_WEAPON,
                quality = 4,
                minItemLevel = 61,
                maxItemLevel = 95,
                matRate = 1.000,
                minAmount = 1,
                maxAmount = 2,
                amountOfMats = 1.666,
            },
        },
    },
}

local d = {}

for itemStr, v in pairs(INFO) do
    for _, sourceInfo in ipairs(v.sourceInfo) do
        d[sourceInfo.classId] = d[sourceInfo.classId] or {}
        d[sourceInfo.classId][sourceInfo.quality] = d[sourceInfo.classId][sourceInfo.quality] or {}

        local dd = d[sourceInfo.classId][sourceInfo.quality]
        local k = sourceInfo.minItemLevel .. ',' .. sourceInfo.maxItemLevel

        dd[k] = dd[k] or
                    {minItemLevel = sourceInfo.minItemLevel, maxItemLevel = sourceInfo.maxItemLevel, possibles = {}}

        table.insert(dd[k].possibles, {
            itemId = tonumber(itemStr:match('i:(%d+)')),
            rate = sourceInfo.matRate,
            minAmount = sourceInfo.minAmount,
            maxAmount = sourceInfo.maxAmount,
        })
    end
end

local function ff(data)
    local r = {}
    for k, v in pairs(data) do
        table.insert(r, v)
    end
    table.sort(r, function(a, b)
        return a.minItemLevel < b.minItemLevel
    end)
    return r
end

for classId, v in pairs(d) do
    for quality, data in pairs(v) do
        v[quality] = ff(data)
    end
end

local p = require('pl.pretty')
local f = require('pl.file')

f.write('Z.lua', 'a=' .. p.write(d))
